feat: add helm-build
naviteq/github-actions pull request #16
Opened 2022-12-13 13:50 UTC by KFearsoff

2022-12-13 15:16 UTC, DovnarAlexander requested changes

2022-12-13 15:16 UTC, DovnarAlexander commented on .github/workflows/helm-release.yaml
> +        if: ${{ github.ref_type == 'tag' }}
Should be executed every time, not only for tags.

2022-12-13 15:16 UTC, DovnarAlexander commented on .github/workflows/helm-release.yaml
>        - name: Commit file to branch
Should be the latest step dependent on previous ones

2022-12-13 15:23 UTC, KFearsoff commented
Fixed

2022-12-14 08:14 UTC, DovnarAlexander requested changes

2022-12-14 08:14 UTC, DovnarAlexander commented on .github/workflows/helm-release.yaml
>        - name: Commit file to branch
Should be `needs` block here to build direct dependency

2022-12-14 08:14 UTC, DovnarAlexander commented on .github/workflows/helm-release.yaml
> +        run: helm package .
Should be `needs` block here to build direct dependency to do that step only after `Update versions` and `Lint`

2022-12-14 08:17 UTC, DovnarAlexander approved these changes

2022-12-14 08:17 UTC, merged